[package]
name = "findkeepassword"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"
description = "Find a forgotten kdbx 4 password by trying many of them"

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
color-eyre = "0.6.2"
eyre = "0.6.8"
kdbx4 = "0.5.1"
rayon = "1.6.1"
