[package]
name = "findkeepassword"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"
description = "Find a forgotten kdbx 4 password by trying many of them"

[dependencies]
kdbx4 = "0.5.1"
clap = {version = "4.0.2", features = ["derive"]}
anyhow = "1.0.57"
rayon = "1.5.3"
