[package]
name = "findkeepassword"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"

[dependencies]
kdbx4 = "0.5.1"
clap = {version = "3.0.10", features = ["cargo"]}
anyhow = "1.0.52"
rayon = "1.5.1"
