[package]
name = "findkeepassword"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2018"

[dependencies]
kdbx4 = "0.5.1"
clap = {version = "2.33.3", features = ["yaml"]}
anyhow = "1.0.45"
rayon = "1.5.1"
